apiVersion: apps/v1   # 메니페스트 버전
kind: Deployment      # 메니페스트 객체 종류
metadata:             # k8s 객체 식별 정보
  name: {{ .Values.deployment.name }}     # 배포 이름
  labels:             # 리소스 식별 이름
    app: nginx
spec:                 # 객체 설정
  replicas: {{ .Values.replicaCount }}         # 복제 계수
  selector:           # 디플로이먼트가 관리할 대상
    matchLabels:
      app:  {{ .Values.deployment.app }}
  template:           # 파드 생성 규칙
    metadata:
      name:  {{ .Values.deployment.name }}
      labels:         # 생성한 파드의 레이블
        app:  {{ .Values.deployment.app }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tags }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80   # 포트 지정
              protocol: TCP
      restartPolicy: Always
